; MESH AutoIncluder Init Script Version 0.1
; Mesh - ModulE Scripting Helper
;
; This file is part of MESH Version 0.5.2010-01-30
; Template was autogenerated by mesh.ahk
;
; !!! DO NOT EDIT THIS FILE, SINCE IT WILL BE DELETED ON EACH RUN !!!
;
Gosub, AutoExecute
Return

AutoExecute:
	;Basic Initialization
	#SingleInstance
	#NoEnv
	SetWorkingDir, %A_ScriptDir%
	OnExit, MeshOnExit

	; Set Version Info for modules
	MeshVersionMajor := "0"
	MeshVersionMinor := "5"
	MeshVersionBuild := "2010-01-30"

	; Initialize all modules
	; Module ModuleManager.ahk
	Gosub, ModuleManagerAutoExecute
	; Module fs.ahk
	Gosub, fsAutoExecute
	; Module BaseGui.ahk
	Gosub, BaseGuiAutoExecute

	mHelper_OverrideOrPreExec()

	; Initialize GUI for mesh
	Gosub, MeshGuiDefaultInit

	mHelper_PostExec()
Return

MeshOnExit:
	mHelper_OverrideOrPreExec()

	AvailModules := mCore_get("AvailModules")
	Loop,Parse,AvailModules,`n
	{
		If ( IsLabel( A_LoopField "OnExit" ) )
		{
			Gosub, % A_LoopField "OnExit"
		}
	}

	mHelper_PostExec()

	ExitApp
Return

; Include the mesh.core files
#Include C:\Dokumente und Einstellungen\ITholic\Eigene Dateien\AutoHotkey\Projekte\PureMESH

; GUI Builder and its subroutines
#Include mesh.core\mesh.gui.ahk
; Hotkeys
#Include mesh.core\mesh.hotkeys.ahk
; Communication
#Include mesh.core\mesh.communication.ahk
; Memory Core Ops
#Include mesh.core\mesh.mCore.ahk
; Generic Constructors
#Include mesh.core\mesh.constructors.ahk
; Generic Helper
#Include mesh.core\mesh.helper.ahk

; The modules to include into Mesh
#Include modules.available\ModuleManager.ahk
#Include modules.available\ModuleManager\moduleManagerFun.ahk
#Include modules.available\ModuleManager\moduleManagerGui.ahk
#Include modules.available\ModuleManager\moduleManagerSub.ahk
#Include modules.available\fs.ahk
#Include modules.available\BaseGui.ahk